#!/usr/bin/env python3
"""Generate `deepgemm/kernels/wgmma.h` — the Hopper (SM90a) WGMMA layer.

Why generated: every `wgmma.mma_async` N-variant needs a *literal* register
list in its inline-asm string (`{%0,%1,...%N/2-1}`), so a portable C++
function-per-N would be ~400 hand-written lines.  The asm forms below are
verbatim from upstream DeepGEMM `ptx/wgmma.cuh` cross-checked against CUTLASS
`cute/arch/mma_sm90_gmma.hpp`:

  FP8   (SS, k32, e4m3x2 — no transpose args, TN-only):
    wgmma.mma_async.sync.aligned.m64nNk32.f32.e4m3.e4m3 {d}, aDesc, bDesc, p, 1, 1;
  BF16  (SS, k16, with transpose immediates for MN-major operands):
    wgmma.mma_async.sync.aligned.m64nNk16.f32.bf16.bf16 {d}, aDesc, bDesc, p, 1, 1, tA, tB;
  TF32  (RS, k8 — A in registers):
    wgmma.mma_async.sync.aligned.m64nNk8.f32.tf32.tf32 {d}, {a0,a1,a2,a3}, bDesc, p, 1, 1;

Also emits the SM90 *GMMA shared-memory descriptor* (a different bit layout
from the SM100 UMMA SmemDescriptor) and the warpgroup control ops.

Regenerate with:  python3 scripts/gen_wgmma.py
"""

import os

F8_NS = list(range(8, 257, 8))          # every legal N, multiple of 8
TF32_NS = [8, 16, 32, 64, 128, 256]     # PTIA-legal tf32 N values


def outs(n):
    return ", ".join(f'"+f"(d[{i}])' for i in range(n // 2))


def f8_case(n):
    k = n // 2
    regs = ",".join(f"%{i}" for i in range(k))
    return f"""        case {n}:
            asm volatile(
                "{{\\n"
                ".reg .pred p;\\n"
                "setp.ne.b32 p, %{k + 2}, 0;\\n"
                "wgmma.mma_async.sync.aligned.m64n{n}k32.f32.e4m3.e4m3 "
                "{{{regs}}}, %{k}, %{k + 1}, p, %{k + 3}, %{k + 4};\\n"
                "}}\\n"
                : {outs(n)}
                : "l"(desc_a), "l"(desc_b), "r"(scale_d), "n"(1), "n"(1));
            break;"""


def bf16_case(n):
    k = n // 2
    regs = ",".join(f"%{i}" for i in range(k))
    return f"""        case {n}:
            asm volatile(
                "{{\\n"
                ".reg .pred p;\\n"
                "setp.ne.b32 p, %{k + 2}, 0;\\n"
                "wgmma.mma_async.sync.aligned.m64n{n}k16.f32.bf16.bf16 "
                "{{{regs}}}, %{k}, %{k + 1}, p, %{k + 3}, %{k + 4}, %{k + 5}, %{k + 6};\\n"
                "}}\\n"
                : {outs(n)}
                : "l"(desc_a), "l"(desc_b), "r"(scale_d),
                  "n"(1), "n"(1), "n"(int32_t(kTransA)), "n"(int32_t(kTransB)));
            break;"""


def tf32_case(n):
    k = n // 2
    regs = ",".join(f"%{i}" for i in range(k))
    return f"""        case {n}:
            asm volatile(
                "{{\\n"
                ".reg .pred p;\\n"
                "setp.ne.b32 p, %{k + 5}, 0;\\n"
                "wgmma.mma_async.sync.aligned.m64n{n}k8.f32.tf32.tf32 "
                "{{{regs}}}, {{%{k}, %{k + 1}, %{k + 2}, %{k + 3}}}, %{k + 4}, p, %{k + 6}, %{k + 7};\\n"
                "}}\\n"
                : {outs(n)}
                : "r"(a0), "r"(a1), "r"(a2), "r"(a3), "l"(desc_b),
                  "r"(scale_d), "n"(1), "n"(1));
            break;"""


HEADER = """// ===========================================================================
// wgmma.h — Hopper (SM90a) WGMMA layer.  AUTO-GENERATED by scripts/gen_wgmma.py
// — do not edit by hand.  Concatenated after prelude.h by the JIT engine.
//
// WGMMA vs tcgen05 (the two tensor-core generations this crate targets):
//
//   SM90  Hopper:  wgmma.mma_async — *warp-group* MMA.  One warpgroup (4
//          warps, 128 threads) cooperates; accumulators live in REGISTERS
//          (N/2 floats per lane), operands come from SMEM via 64-bit
//          "GMMA descriptors" (or registers, the "RS" form).  Asynchronous:
//          issue -> wgmma.commit_group -> wgmma.wait_group.
//
//   SM100 Blackwell: tcgen05.mma — *single-thread-issue* MMA writing
//          accumulators into TMEM (tensor memory), read back with
//          tcgen05.ld.  (See prelude.h.)
//
// Register layout of an m64nN accumulator (per lane), used by every SM90
// epilogue in this crate:
//
//   row_idx = lane / 4          col_idx = lane % 4
//   r0 = warp_row_base + row_idx        (warp w owns rows [16w, 16w+16))
//   r1 = r0 + 8
//   acc[i*4+0], acc[i*4+1] -> row r0, cols 8i + col_idx*2 + {0,1}
//   acc[i*4+2], acc[i*4+3] -> row r1, same columns
// ===========================================================================
namespace dg {

// ---------------------------------------------------------------------------
// SM90 GMMA shared-memory descriptor (DIFFERENT bit layout from SM100!):
//   [0,14)  start_address = smem_addr >> 4        [49,52) base_offset
//   [16,30) leading_byte_offset (LBO) >> 4        [62,64) layout_type
//   [32,46) stride_byte_offset  (SBO) >> 4             0=INTERLEAVE 1=B128
//                                                       2=B64 3=B32
// ---------------------------------------------------------------------------
union GmmaDescriptor {
    uint64_t desc_;
    struct {
        uint16_t start_address_ : 14, : 2;
        uint16_t leading_byte_offset_ : 14, : 2;
        uint16_t stride_byte_offset_ : 14, : 2;
        uint8_t : 1, base_offset_ : 3, : 4;
        uint8_t : 6, layout_type_ : 2;
    };
    struct { uint32_t lo, hi; };
};
static_assert(sizeof(GmmaDescriptor) == 8, "bad gmma desc size");

enum class GmmaLayoutType : uint8_t {
    INTERLEAVE = 0, B128 = 1, B64 = 2, B32 = 3,
};

DG_DEVICE GmmaDescriptor make_gmma_desc(const void* smem_ptr, GmmaLayoutType layout,
                                        uint32_t leading_byte_offset, uint32_t stride_byte_offset) {
    GmmaDescriptor d;
    d.desc_ = 0;
    d.layout_type_ = (uint8_t)layout;
    d.start_address_ = (uint16_t)(cvta_shared_to_u32(smem_ptr) >> 4);
    d.base_offset_ = 0;
    d.stride_byte_offset_ = (uint16_t)(stride_byte_offset >> 4);
    d.leading_byte_offset_ = (uint16_t)(leading_byte_offset >> 4);
    return d;
}

// Advance a descriptor by a raw byte offset (low 32 bits hold start+LBO;
// LBO is 0 for the swizzled K-major layouts, so plain addition is exact).
DG_DEVICE void advance_gmma_desc(GmmaDescriptor& d, uint32_t byte_offset) {
    d.lo += byte_offset >> 4;
}

// ---------------------------------------------------------------------------
// Warpgroup control flow
// ---------------------------------------------------------------------------
DG_DEVICE void warpgroup_fence_operand(float& reg) {
    // Empty asm with "+f": forces ptxas to materialize the accumulator in a
    // register across the async wgmma window (operand stability).
    asm volatile("" : "+f"(reg) :: "memory");
}
DG_DEVICE void warpgroup_arrive() { asm volatile("wgmma.fence.sync.aligned;" ::: "memory"); }
DG_DEVICE void warpgroup_commit_batch() { asm volatile("wgmma.commit_group.sync.aligned;" ::: "memory"); }
template <int kNumRemainingWaits>
DG_DEVICE void warpgroup_wait_group() {
    asm volatile("wgmma.wait_group.sync.aligned %0;" :: "n"(kNumRemainingWaits) : "memory");
}

// ---------------------------------------------------------------------------
// Instruction families (N selected by a switch — every case's asm string is
// generated because the register list is a literal)
// ---------------------------------------------------------------------------
// FP8 E4M3 x E4M3 -> FP32, m64nNk32, both operands from SMEM.  FP8 WGMMA is
// TN-only (no transpose immediates).  scale_d: 0 = overwrite (D = A*B),
// 1 = accumulate.  First instruction of a K-block uses scale_d=0 so the
// accumulator may hold garbage between blocks.
template <uint32_t N>
DG_DEVICE void wgmma_f8(uint64_t desc_a, uint64_t desc_b, float* d, uint32_t scale_d) {
    switch (N) {
"""

FOOTER = """        default: DG_STATIC_ASSERT(N == 0, "unsupported wgmma_f8 N");
    }
}

// BF16 x BF16 -> FP32, m64nNk16.  kTransA/kTransB: 0 = K-major (row) operand,
// 1 = MN-major (col) operand — maps to the wgmma "transpose" immediates
// (GMMA::Major::K = 0, GMMA::Major::MN = 1).
template <uint32_t N, uint32_t kTransA, uint32_t kTransB>
DG_DEVICE void wgmma_bf16(uint64_t desc_a, uint64_t desc_b, float* d, uint32_t scale_d) {
    switch (N) {
"""

FOOTER2 = """        default: DG_STATIC_ASSERT(N == 0, "unsupported wgmma_bf16 N");
    }
}

// TF32 x TF32 -> FP32, m64nNk8, "RS" form: the A operand lives in 4
// registers per lane (an 8-column k-slice of the 64x8 A tile), B from SMEM.
// Used by the hyperconnection prenorm GEMM (fp32 weights, tf32 compute).
template <uint32_t N>
DG_DEVICE void wgmma_tf32_rs(float a0, float a1, float a2, float a3,
                             uint64_t desc_b, float* d, uint32_t scale_d) {
    switch (N) {
"""

FOOTER3 = """        default: DG_STATIC_ASSERT(N == 0, "unsupported wgmma_tf32 N");
    }
}

} // namespace dg
"""


def main():
    parts = [HEADER]
    parts.append("\n".join(f8_case(n) for n in F8_NS))
    parts.append(FOOTER)
    parts.append("\n".join(bf16_case(n) for n in F8_NS))
    parts.append(FOOTER2)
    parts.append("\n".join(tf32_case(n) for n in TF32_NS))
    parts.append(FOOTER3)
    out = "\n".join(parts) + "\n"
    path = os.path.join(os.path.dirname(__file__), "..", "deepgemm", "kernels", "wgmma.h")
    with open(path, "w") as f:
        f.write(out)
    print(f"wrote {os.path.normpath(path)}: {len(out.splitlines())} lines, "
          f"{len(F8_NS)} f8 + {len(F8_NS)} bf16 + {len(TF32_NS)} tf32 variants")


if __name__ == "__main__":
    main()
