#!/usr/bin/env python3
"""Offline NVRTC compile check for the sparse MQA (DSA top-k indexer) kernels.

Compiles the metadata scheduler kernel and both scoring-kernel variants
(contiguous flat KV + paged fused KV) of deepgemm/kernels/sparse_mqa_sm100.cu
to PTX (compute_100a — what the runtime JIT uses) and to SASS (sm_100a via
nvrtcGetCUBIN, running the built-in ptxas backend), printing sizes.

No GPU or CUDA toolkit needed — only pip's nvidia-cuda-nvrtc-cu12
(pattern: scripts/dbg_nvrtc.py, deepgemm/src/jit.rs compile_check_kernel).

The wrapper bodies below are the canonical instantiations and mirror the
strings generated by deepgemm/src/api_sparse_mqa.rs for:
  heads=16/32, fp8/fp4, sparse_block_kv=8/16, nmax=512, page_kv=64, sms=148.
"""
import ctypes
import sys

NVRTC = "/home/z/.venv/lib/python3.12/site-packages/nvidia/cuda_nvrtc/lib/libnvrtc.so.12"
ROOT = "/home/z/my-project/deepgemm-rs/deepgemm/kernels/"

# Canonical configs (keep in sync with tests/sparse_mqa_cpu.rs).
NUM_SMS = 148
NMAX = 512
SPLIT_KV = {"fp8": 512, "fp4": 640}  # dtype -> split
MATH_WGS = {"fp8": 4, "fp4": 5}
KV_STAGES = {"fp8": 3, "fp4": 5}
Q_STAGES, TMEM_STAGES, BLOCK_Q, THREADS, SPLITS_PER_ENTRY = 2, 5, 2, 256, 8


def align(v, a):
    return (v + a - 1) // a * a


def meta_smem(nmax, split_kv, sbkv):
    warps = THREADS // 32
    bps = split_kv // sbkv
    max_merged = BLOCK_Q * nmax
    max_splits = (max_merged + bps - 1) // bps
    b = (BLOCK_Q * nmax + max_merged + max_splits) * 4
    b += warps * 4
    b += (1 + warps * (SPLITS_PER_ENTRY + 1)) * 4
    b = align(b, 16)
    b += align((3 + BLOCK_Q) * 4, 16)  # alignas(16) q_block struct
    b += 4                             # is_last_cta
    return align(b, 128)


def logits_smem(dtype, sbkv):
    pack = 2 if dtype == "fp4" else 1
    skv = SPLIT_KV[dtype]
    kvs = KV_STAGES[dtype]
    bpt = 128 // pack  # bytes per token
    swz = 8 * 128 // pack
    q = Q_STAGES * (BLOCK_Q * 32) * bpt
    kv_off = align(q, swz)
    sfq_off = align(kv_off + kvs * skv * bpt, 128)
    sfkv_off = align(sfq_off + Q_STAGES * 128 * 4, 128)
    w_off = align(sfkv_off + kvs * skv * 4, 128)
    kvi_off = align(w_off + Q_STAGES * (BLOCK_Q * 32) * 2, 16)
    bps = skv // sbkv
    qb_off = align(kvi_off + kvs * bps * 8, 16)
    hdr_off = align(qb_off + Q_STAGES * 16, 16)
    bar_off = align(hdr_off + kvs * 16, 8)
    bar = (3 * Q_STAGES + 4 * kvs + 2 * TMEM_STAGES) * 8
    return align(bar_off + bar + 4, swz)


def meta_body(paged, uks, sbkv, page_kv):
    skv = SPLIT_KV["fp8"]
    bps = skv // sbkv
    smem = meta_smem(NMAX, skv, sbkv)
    return f"""
extern "C" __global__ void __dg_kernel(
    unsigned num_q_tokens, unsigned num_kv_tokens,
    const unsigned* cu_seq_len_k_start, const unsigned* cu_seq_len_k_end,
    const unsigned* context_lens, const unsigned* block_table, unsigned block_table_stride,
    const unsigned* indices,
    const unsigned* sparse_kv_block_indices, unsigned char* metadata, unsigned char* workspace) {{
    static_assert((sizeof(dg::SparseMetaSmem<{BLOCK_Q}, {NMAX}, {bps}, {SPLITS_PER_ENTRY}, {THREADS}>) + 127) / 128 * 128 == {smem},
                  "sparse-MQA metadata smem layout drift");
    dg::sparse_mqa_metadata_impl<{int(paged)}, {int(uks)}, {BLOCK_Q}, {skv}, {sbkv}, {NMAX}, {page_kv}, {SPLITS_PER_ENTRY}, {NUM_SMS}, {THREADS}>(
        num_q_tokens, num_kv_tokens, cu_seq_len_k_start, cu_seq_len_k_end, context_lens,
        block_table, block_table_stride, indices, sparse_kv_block_indices, metadata, workspace);
}}
"""


def logits_body(paged, dtype, heads, sbkv, uks, page_kv):
    skv = SPLIT_KV[dtype]
    kvs = KV_STAGES[dtype]
    mwg = MATH_WGS[dtype]
    fp4 = 1 if dtype == "fp4" else 0
    smem = logits_smem(dtype, sbkv)
    if paged:
        return f"""
extern "C" __global__ void __dg_kernel(
    unsigned logits_stride, unsigned kv_page_stride_bytes, unsigned short* logits,
    const unsigned char* fused_kv_cache, const unsigned char* metadata,
    const __grid_constant__ dg::TmaMap tma_q,
    const __grid_constant__ dg::TmaMap tma_sf_q,
    const __grid_constant__ dg::TmaMap tma_w) {{
    static_assert(sizeof(dg::SparseLogitsSmem<{BLOCK_Q}, {sbkv}, {skv}, {Q_STAGES}, {kvs}, {TMEM_STAGES}, {fp4}>) == {smem},
                  "sparse-MQA logits smem layout drift");
    dg::sparse_mqa_logits_paged_impl<{heads}, {page_kv}, {sbkv}, {Q_STAGES}, {kvs}, {TMEM_STAGES}, {mwg}, {NUM_SMS}, {BLOCK_Q}, {fp4}>(
        logits_stride, kv_page_stride_bytes, logits, fused_kv_cache, metadata, tma_q, tma_sf_q, tma_w);
}}
"""
    return f"""
extern "C" __global__ void __dg_kernel(
    unsigned logits_stride, unsigned num_kv_tokens, unsigned short* logits,
    const unsigned char* kv, const unsigned int* sf_kv, const unsigned char* metadata,
    const __grid_constant__ dg::TmaMap tma_q,
    const __grid_constant__ dg::TmaMap tma_sf_q,
    const __grid_constant__ dg::TmaMap tma_w,
    const __grid_constant__ dg::TmaMap tma_kv,
    const __grid_constant__ dg::TmaMap tma_sf_kv) {{
    static_assert(sizeof(dg::SparseLogitsSmem<{BLOCK_Q}, {sbkv}, {skv}, {Q_STAGES}, {kvs}, {TMEM_STAGES}, {fp4}>) == {smem},
                  "sparse-MQA logits smem layout drift");
    dg::sparse_mqa_logits_impl<{heads}, {sbkv}, {Q_STAGES}, {kvs}, {TMEM_STAGES}, {mwg}, {NUM_SMS}, {BLOCK_Q}, {int(uks)}, {fp4}>(
        logits_stride, num_kv_tokens, logits, kv, sf_kv, metadata,
        tma_q, tma_sf_q, tma_w, tma_kv, tma_sf_kv);
}}
"""


def compile(l, name, src, arch, want_cubin):
    prog = ctypes.c_void_p()
    rc = l.nvrtcCreateProgram(ctypes.byref(prog), src, b"verify.cu", 0, None, None)
    assert rc == 0, rc
    opts = [b"--gpu-architecture=" + arch.encode(), b"--std=c++17"]
    arr = (ctypes.c_char_p * len(opts))(*[ctypes.c_char_p(o) for o in opts])
    rc = l.nvrtcCompileProgram(prog, len(opts), arr)
    if rc != 0:
        n = ctypes.c_size_t()
        l.nvrtcGetProgramLogSize(prog, ctypes.byref(n))
        buf = ctypes.create_string_buffer(n.value + 1)
        l.nvrtcGetProgramLog(prog, buf)
        printed = 0
        for ln in buf.value.decode(errors="replace").splitlines():
            if ("error" in ln or "note" in ln or "^" in ln) and printed < 50:
                print(ln)
                printed += 1
        print(f"FAIL: {name} ({arch})")
        sys.exit(1)
    n = ctypes.c_size_t()
    if want_cubin:
        l.nvrtcGetCUBINSize(prog, ctypes.byref(n))
        return n.value
    l.nvrtcGetPTXSize(prog, ctypes.byref(n))
    return n.value


def main():
    l = ctypes.CDLL(NVRTC)
    prelude = open(ROOT + "prelude.h").read()
    tu = open(ROOT + "sparse_mqa_sm100.cu").read()

    variants = [
        ("metadata-contig", meta_body(False, False, 8, 0)),
        ("metadata-paged", meta_body(True, False, 8, 64)),
        ("logits-contig-fp8-sb8", logits_body(False, "fp8", 16, 8, False, 0)),
        ("logits-contig-fp4-sb16-uks", logits_body(False, "fp4", 16, 16, True, 0)),
        ("logits-paged-fp8-sb16", logits_body(True, "fp8", 32, 16, False, 64)),
        ("logits-paged-fp4-sb8", logits_body(True, "fp4", 16, 8, False, 64)),
    ]
    ok = True
    print(f"{'variant':<28} {'PTX compute_100a':>18} {'SASS sm_100a':>14}")
    for name, body in variants:
        src = (prelude + "\n" + tu + "\n" + body).encode()
        ptx = compile(l, name, src, "compute_100a", want_cubin=False)
        sass = compile(l, name, src, "sm_100a", want_cubin=True)
        ok = ok and ptx > 0 and sass > 0
        print(f"{name:<28} {ptx:>15} B  {sass:>11} B")
    print("ALL OK" if ok else "FAILURES")
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
